export const dummyData = [
  {
    id: "f1a1f0d0-aaaafjbjdsb-4aaa-baaa-aaaaaaaaaaaa",
    name: "PDF files",
    path: "/home/Pdf Files",
    size: 0,
    type: "folder",
    fileUrl: "/home/Documents",
    thumbnailUrl: null,
    userId: "user-123",
    parentId: null,
    isFolder: true,
    isStarred: false,
    isTrash: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "f1a1f0d0-aaaa-4aaadsjbja-baaa-aaaaaaaaaaaa",
    name: "Documents",
    path: "/home/Mint",
    size: 0,
    type: "folder",
    fileUrl: "/home/Mint",
    thumbnailUrl: null,
    userId: "user-123",
    parentId: null,
    isFolder: true,
    isStarred: false,
    isTrash: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "f1a1f0d0-aaaa-4aaa-baaafid-aaaaaaaaaaaa",
    name: "Documents",
    path: "/home/My Data",
    size: 0,
    type: "folder",
    fileUrl: "/home/My Data",
    thumbnailUrl: null,
    userId: "user-123",
    parentId: null,
    isFolder: true,
    isStarred: false,
    isTrash: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // Folders
  {
    id: "f1a1f0d0-aaaa-4aaa-baaa-aaaaaaaaaaaa",
    name: "Documents",
    path: "/home/Documents",
    size: 0,
    type: "folder",
    fileUrl: "/home/Documents",
    thumbnailUrl: null,
    userId: "user-123",
    parentId: null,
    isFolder: true,
    isStarred: false,
    isTrash: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "f1a1f0d0-bbbb-4bbb-bbbb-bbbbbbbbbbbb",
    name: "Pictures",
    path: "/home/Pictures",
    size: 0,
    type: "folder",
    fileUrl: "/home/Pictures",
    thumbnailUrl: null,
    userId: "user-123",
    parentId: null,
    isFolder: true,
    isStarred: false,
    isTrash: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "f1a1f0d0-cccc-4ccc-bccc-cccccccccccc",
    name: "Videos",
    path: "/home/Videos",
    size: 0,
    type: "folder",
    fileUrl: "/home/Videos",
    thumbnailUrl: null,
    userId: "user-123",
    parentId: null,
    isFolder: true,
    isStarred: false,
    isTrash: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "f1a1f0d0-dddd-4ddd-bddd-dddddddddddd",
    name: "Music",
    path: "/home/Music",
    size: 0,
    type: "folder",
    fileUrl: "/home/Music",
    thumbnailUrl: null,
    userId: "user-123",
    parentId: null,
    isFolder: true,
    isStarred: false,
    isTrash: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },

  // Files
  {
    id: "f2b2f0d0-aaaa-4aaa-baaa-aaaaaaaaaaaa",
    name: "resume.pdf",
    path: "/home/resume.pdf",
    size: 120_000,
    type: "application/pdf",
    fileUrl: "/files/resume.pdf",
    thumbnailUrl: null,
    userId: "user-123",
    parentId: null,
    isFolder: false,
    isStarred: false,
    isTrash: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "f2b2f0d0-bbbb-4bbb-bbbb-bbbbbbbbbbbb",
    name: "profile.jpg",
    path: "/home/profile.jpg",
    size: 240_000,
    type: "image/jpeg",
    fileUrl: "/files/profile.jpg",
    thumbnailUrl: "/thumbnails/profile.jpg",
    userId: "user-123",
    parentId: null,
    isFolder: false,
    isStarred: false,
    isTrash: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "f2b2f0d0-cccc-4ccc-bccc-cccccccccccc",
    name: "video.mp4",
    path: "/home/video.mp4",
    size: 5_000_000,
    type: "video/mp4",
    fileUrl: "/files/video.mp4",
    thumbnailUrl: "/thumbnails/video.jpg",
    userId: "user-123",
    parentId: null,
    isFolder: false,
    isStarred: false,
    isTrash: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "f2b2f0d0-dddd-4ddd-bddd-dddddddddddd",
    name: "song.mp3",
    path: "/home/song.mp3",
    size: 3_500_000,
    type: "audio/mpeg",
    fileUrl: "/files/song.mp3",
    thumbnailUrl: null,
    userId: "user-123",
    parentId: null,
    isFolder: false,
    isStarred: false,
    isTrash: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "f2b2f0d0-eeee-4eee-beee-eeeeeeeeeeee",
    name: "notes.txt",
    path: "/home/notes.txt",
    size: 8_000,
    type: "text/plain",
    fileUrl: "/files/notes.txt",
    thumbnailUrl: null,
    userId: "user-123",
    parentId: null,
    isFolder: false,
    isStarred: false,
    isTrash: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "f2b2f0d0-ffff-4fff-bfff-ffffffffffff",
    name: "presentation.pptx",
    path: "/home/presentation.pptx",
    size: 1_500_000,
    type: "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    fileUrl: "/files/presentation.pptx",
    thumbnailUrl: null,
    userId: "user-123",
    parentId: null,
    isFolder: false,
    isStarred: false,
    isTrash: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
